"""unique_constraint_to_name_fields

Revision ID: 5d0d1098584f
Revises: 1f07eda78695
Create Date: 2026-08-18 14:04:20.502087

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5d0d1098584f"
down_revision: str | Sequence[str] | None = "1f07eda78695"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "agonists", ["name"])
    op.create_unique_constraint(None, "exercises", ["name"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "exercises", type_="unique")
    op.drop_constraint(None, "agonists", type_="unique")
    # ### end Alembic commands ###
