"""preinitial schema

Revision ID: f142373e00f4
Revises:
Create Date: 2026-08-07 20:52:12.672700

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f142373e00f4"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "agonists",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "exercises",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "workouts",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("planned_start_time", sa.DateTime(timezone=True), nullable=True),
        sa.Column("planned_end_time", sa.DateTime(timezone=True), nullable=True),
        sa.Column("actual_start_time", sa.DateTime(timezone=True), nullable=True),
        sa.Column("actual_end_time", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "exercise_agonist",
        sa.Column("exercise_id", sa.Uuid(), nullable=False),
        sa.Column("agonist_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["agonist_id"], ["agonists.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["exercise_id"], ["exercises.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("exercise_id", "agonist_id"),
    )
    op.create_table(
        "workout_sets",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("order", sa.Integer(), nullable=True),
        sa.Column("planned_reps", sa.Integer(), nullable=False),
        sa.Column("planned_weight", sa.Float(), nullable=False),
        sa.Column("actual_reps", sa.Integer(), nullable=False),
        sa.Column("actual_weight", sa.Float(), nullable=False),
        sa.Column("workout_id", sa.Uuid(), nullable=False),
        sa.Column("exercise_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["exercise_id"], ["exercises.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["workout_id"], ["workouts.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("workout_sets")
    op.drop_table("exercise_agonist")
    op.drop_table("workouts")
    op.drop_table("exercises")
    op.drop_table("agonists")
    # ### end Alembic commands ###
